<!DOCTYPE HTML>
<html lang="en-GB">
	<head>
		<?php echo $head; ?>
	</head>
	<body>
		<div id="header">
			<h1><?php echo $content->title; ?></h1>
		</div>
		<div id="content">
			<div id="page">
			<?php echo $content->cached_content; ?>

			<?php if (isset($tags)) : ?>
			<div class="meta tags clear">
				<h2>Tags</h2>
				<ul>
					<?php foreach ($tags as $tag) : ?>
					<li>
						<?php echo Html::anchor('/tag/'.$tag, $tag->name, array('rel' => 'tag'))?>
						<a href="#" rel="tag">tag</a>
					</li>
					<?php endforeach; ?>
				</ul>
			</div>
			<?php endif; ?>
			</div>
			<?php if (isset($content->next) or isset($content->previous)) :?>
			<div class="controls clear">
				<?php if ($content->next) : ?>
					<?php echo Html::anchor(date('Y/m/d/', $content->next->created).$content->next->slug, $content->next->title.' &rsaquo', array('class' => 'float-right')); ?>
				<?php endif; ?>
				<?php if ($content->prev) : ?>
					<?php echo Html::anchor(date('Y/m/d/', $content->prev->created).$content->prev->slug, '&lsaquo '.$content->prev->title, array('class' => 'float-left')); ?>
				<?php endif; ?>
			</div>
			<?php endif; ?>
		</div>
		<?php echo $pages; ?>
		<div id="user-state">
		<?php if (isset($user)) : ?>
			<p>Bienvenue <?php echo ($user->name); ?>! <?php echo Html::anchor(Route::get('login')->uri(array('action' => 'logout')), 'Logout'); ?></p>
		<?php else : ?>
			<p>Bonjour! <?php echo Html::anchor(Route::get('login')->uri(array('action' => 'login')), 'Login'); ?></p>
		<?php endif; ?>
		</div>
		<?php echo $footer; ?>
	</body>
</html>